on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

name: Standard Build

jobs:
  ci:
    name: CI - Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install Dependencies
      - run: yarn install

      - name: Run Tests
      - run: yarn test

      - name: Build
      - run: yarn build

      - name: Check File Existence
      - uses: ./
        id: actions-check-files
        with:
          files: 'fragments/*, src/index.ts'
