on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

name: Standard Build

jobs:
  ci:
    name: CI - Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - run: yarn install
      - run: yarn test
      - run: yarn build

  check_file_existence:
    name: Check File Existence
    id: actions-check-files
    if: ${{ success() }}
    needs: [ci]
    steps:
      uses: ./
      with:
        files: 'fragments/*, src/index.ts'
