on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

name: Standard Build

jobs:
  ci:
    name: CI - Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Checkout code

      - uses: actions/setup-node@v3
      - name: Setup Node
        with:
          node-version: 18
          cache: yarn
      - run: yarn install
      - run: yarn test
      - run: yarn build

      - uses: ./
      - name: Check File Existence
        id: actions-check-files
        with:
          files: 'fragments/*, src/index.ts'
